-- Ensure the import connection reads this script as UTF-8.
SET NAMES utf8mb4;

INSERT INTO `questions` (`id`, `text`, `content`, `active`, `order_index`) VALUES
(1,
'01 — SERÁ QUE FOI DEUS QUEM CRIOU A PENA DE MORTE? FAÇA O DOWNLOAD DA BÍBLIA ONLINE E CONHEÇA O AUTOR DA PENA DE MORTE: GÊNESIS 9:5, 6.',
'[{"bold":true,"text":"PENA DE MORTE: SIM OU NÃO?\\n01 — SERÁ QUE FOI DEUS QUEM CRIOU A PENA DE MORTE? ","color":"#0000FF"},{"bold":true,"text":"FAÇA O DOWNLOAD DA BÍBLIA ONLINE ","color":"#FF0000"},{"bold":true,"text":"E CONHEÇA O AUTOR DA PENA DE MORTE: GÊNESIS 9:5, 6.","color":"#008000"}]',
1,1);

INSERT INTO `questions` (`id`, `text`, `content`, `active`, `order_index`) VALUES
(2,
'02 — O AUTOR DO APP, MISTER GANDHI, AFIRMA QUE A "LEI DA PENA DE MORTE" JÁ ESTÁ INSTAURADA NO BRASIL. SEGUNDO ELE, ELA É SANCIONADA PELA CONSTITUIÇÃO (ART. 228: OS MENORES DE 18 ANOS SÃO PENALMENTE INIMPUTÁVEIS), RATIFICADA PELO CONGRESSO ATRAVÉS DO ART. 27 DO CÓDIGO PENAL, PELO ART. 104 DO ECA (ESTATUTO DA CRIANÇA E DO ADOLESCENTE) E HOMOLOGADA PELO STF, SENDO CONSIDERADA APENAS UM "ATO INFRACIONAL". NA VERDADE, O QUE ESTES ARTIGOS DIZEM É QUE OS MENORES DE 18 ANOS PODEM FAZER TUDO, INCLUSIVE MATAR. VOCÊ ACHA QUE ELE ESTÁ CERTO?',
'[{"bold":true,"text":"02 — O AUTOR DO APP, MISTER GANDHI, AFIRMA QUE A ","color":"#0000FF"},{"bold":true,"text":"\\"LEI DA PENA DE MORTE\\" JÁ ESTÁ INSTAURADA NO BRASIL","color":"#FF0000"},{"bold":true,"text":". SEGUNDO ELE, ELA É SANCIONADA PELA CONSTITUIÇÃO, RATIFICADA PELO CONGRESSO E HOMOLOGADA PELO STF. VOCÊ ACHA QUE ELE ESTÁ CERTO?","color":"#008000"}]',
1,2);

INSERT INTO `questions` (`id`, `text`, `content`, `active`, `order_index`) VALUES
(3,
'03 — VOCÊ É A FAVOR DA "PENA DE MORTE" PARA FEMINICIDA (ASSASSINO DE MULHER: ESPOSA, NAMORADA, ETC.) E DE QUE OS SEUS BENS SEJAM ESPOLIADOS PARA RESSARCIR OS FAMILIARES DA VÍTIMA? CERCA DE 10 MULHERES SÃO ASSASSINADAS TODOS OS DIAS NO BRASIL. A "LEI MARIA DA PENHA" SÓ DIMINUIU EM 10% O FEMINICÍDIO NO PAÍS.',
'[{"bold":true,"text":"03 — VOCÊ É A FAVOR DA ","color":"#0000FF"},{"bold":true,"text":"\\"PENA DE MORTE\\" PARA FEMINICIDA","color":"#FF0000"},{"bold":true,"text":" E DE QUE OS SEUS BENS SEJAM ESPOLIADOS PARA RESSARCIR OS FAMILIARES DA VÍTIMA? CERCA DE 10 MULHERES SÃO ASSASSINADAS TODOS OS DIAS NO BRASIL.","color":"#008000"}]',
1,3);

INSERT INTO `questions` (`id`, `text`, `content`, `active`, `order_index`) VALUES
(4,
'04 — TALVEZ VOCÊ NÃO SEJA A FAVOR DA "PENA DE MORTE" PARA FEMINICIDAS, MAS VOCÊ CONCORDA COM A "LEI GANDHI ANTI-FEMINICÍDIO" NOS SEGUINTES MOLDES? UMA LEI DE PROTEÇÃO À VIDA E À INTEGRIDADE FÍSICA DA MULHER, BASEADA NA "LEI DA IGUALITARIEDADE DE DIREITOS" E NA "LEI DA JUSTA RECOMPENSA". SE ALGUÉM A AGREDIR, FERIR, MUTILAR, INCENDIAR OU CAUSAR-LHE MALES E DEFORMAÇÕES FÍSICAS, QUE SEJA FEITO O MESMO AO AGRESSOR, NA MESMA PROPORÇÃO. ALÉM DISSO, APLICAR-SE-IA A PENA DE PRISÃO PREVISTA EM LEI COM CUMPRIMENTO INTEGRAL, A ESPOLIAÇÃO DE SEUS BENS PARA INDENIZAR A VÍTIMA E, CASO SEJA NECESSÁRIO O TRANSPLANTE DE ALGUM ÓRGÃO (RINS, PULMÃO, ETC.), O AGRESSOR SERIA UM DOADOR COMPULSÓRIO. SE O ÓRGÃO NÃO FOR COMPATÍVEL COM A VÍTIMA, SERÁ DOADO AO SUS, COLOCANDO A VÍTIMA COMO O PRIMEIRO PACIENTE NA FILA DE ESPERA DE TRANSPLANTE. SIM OU NÃO? (NOTA: CERCA DE 21 MILHÕES DE MULHERES FORAM AGREDIDAS E ESPANCADAS EM 2017 NO BRASIL).',
'[{"bold":true,"text":"04 — TALVEZ VOCÊ NÃO SEJA A FAVOR DA ","color":"#0000FF"},{"bold":true,"text":"\\"LEI GANDHI ANTI-FEMINICÍDIO\\"","color":"#FF0000"},{"bold":true,"text":" NOS SEGUINTES MOLDES? UMA LEI DE PROTEÇÃO À VIDA E À INTEGRIDADE FÍSICA DA MULHER. ","color":"#0000FF"},{"bold":true,"text":"SIM OU NÃO?","color":"#FF0000"},{"bold":true,"text":" (NOTA: CERCA DE 21 MILHÕES DE MULHERES FORAM AGREDIDAS E ESPANCADAS EM 2017 NO BRASIL).","color":"#008000"}]',
1,4);

INSERT INTO `questions` (`id`, `text`, `content`, `active`, `order_index`) VALUES
(5,
'05 — EXISTE JUSTIÇA PARA ASSASSINOS NO BRASIL? SIM OU NÃO? JUSTIÇA É A IGUALDADE DE DIREITO ONDE A PENA É IGUAL AO DELITO; CASO HAJA DESIGUALDADE ENTRE AMBOS, HOUVE INJUSTIÇA. SE A PENA É MAIOR QUE O DELITO, SOMOS INJUSTOS COM O AGRESSOR; SE A PENA É MENOR QUE O DELITO, SOMOS INJUSTOS COM A VÍTIMA.',
'[{"bold":true,"text":"05 — EXISTE JUSTIÇA PARA ASSASSINOS NO BRASIL? ","color":"#0000FF"},{"bold":true,"text":"SIM OU NÃO?","color":"#FF0000"},{"bold":true,"text":" JUSTIÇA É A IGUALDADE DE DIREITO ONDE A PENA É IGUAL AO DELITO; CASO HAJA DESIGUALDADE ENTRE AMBOS, HOUVE INJUSTIÇA.","color":"#008000"}]',
1,5);

INSERT INTO `questions` (`id`, `text`, `content`, `active`, `order_index`) VALUES
(6,
'06 — UM BANDIDO MATA TODA UMA FAMÍLIA, GANHA 30 ANOS DE PRISÃO E SAI APÓS CUMPRIR 1/3 DELA (DEZ ANOS). HOUVE UMA JUSTIÇA PLENA E JUSTA? AQUELAS VIDAS SÓ VALEM DEZ ANOS DE PRISÃO DA VIDA DO ASSASSINO? O DIREITO DO ASSASSINO É MAIOR QUE O DA VÍTIMA? O ASSASSINO É CIDADÃO DE 1ª CLASSE E A VÍTIMA É CIDADÃO DE 2ª? UM É FILHO DE DEUS E O OUTRO É ENTEADO OU FILHO DO DIABO? O ART. 5º DA CONSTITUIÇÃO DIZ: "TODOS SÃO IGUAIS PERANTE A LEI, SEM DISTINÇÃO DE QUALQUER NATUREZA..."',
'[{"bold":true,"text":"06 — UM BANDIDO MATA TODA UMA FAMÍLIA, GANHA 30 ANOS DE PRISÃO E SAI APÓS CUMPRIR 1/3 DELA (DEZ ANOS). ","color":"#0000FF"},{"bold":true,"text":"HOUVE UMA JUSTIÇA PLENA E JUSTA?","color":"#FF0000"},{"bold":true,"text":" O ART. 5º DA CONSTITUIÇÃO DIZ: \\"TODOS SÃO IGUAIS PERANTE A LEI, SEM DISTINÇÃO DE QUALQUER NATUREZA...\\"","color":"#008000"}]',
1,6);

INSERT INTO `questions` (`id`, `text`, `content`, `active`, `order_index`) VALUES
(7,
'07 — VOCÊ É A FAVOR DA "PENA DE MORTE" PARA ASSASSINOS MAIORES DE 18 ANOS E DE QUE OS SEUS BENS SEJAM ESPOLIADOS PARA INDENIZAR A FAMÍLIA DA VÍTIMA? MAIS DE 40 MIL PESSOAS SÃO ASSASSINADAS TODOS OS ANOS NO BRASIL (EM 2017 FORAM CERCA DE 63.800) E, EM 1/3 DAS FAMÍLIAS BRASILEIRAS, HÁ UM ENTE QUERIDO QUE FOI ASSASSINADO.',
'[{"bold":true,"text":"07 — VOCÊ É A FAVOR DA ","color":"#0000FF"},{"bold":true,"text":"\\"PENA DE MORTE\\" PARA ASSASSINOS MAIORES DE 18 ANOS","color":"#FF0000"},{"bold":true,"text":" E DE QUE OS SEUS BENS SEJAM ESPOLIADOS PARA INDENIZAR A FAMÍLIA DA VÍTIMA? MAIS DE 40 MIL PESSOAS SÃO ASSASSINADAS TODOS OS ANOS NO BRASIL.","color":"#008000"}]',
1,7);

INSERT INTO `questions` (`id`, `text`, `content`, `active`, `order_index`) VALUES
(8,
'08 — VOCÊ É A FAVOR DA "PENA DE MORTE" PARA RAPTORES (SEQUESTRADORES) DE PESSOAS PARA TRABALHO SEXUAL OU TRABALHO ESCRAVO E DE QUE OS SEUS BENS SEJAM ESPOLIADOS PARA RESSARCIR OS FAMILIARES DA VÍTIMA? SEGUNDO A ONU, CERCA DE 2,5 MILHÕES DE PESSOAS POR ANO EM TODO O MUNDO SÃO VÍTIMAS DO TRÁFICO INTERNACIONAL — SENDO 2.400.000 MULHERES E METADE CRIANÇAS —, MOVIMENTANDO 150 BILHÕES DE DÓLARES ANUALMENTE.',
'[{"bold":true,"text":"08 — VOCÊ É A FAVOR DA ","color":"#0000FF"},{"bold":true,"text":"\\"PENA DE MORTE\\" PARA RAPTORES","color":"#FF0000"},{"bold":true,"text":" E DE QUE OS SEUS BENS SEJAM ESPOLIADOS PARA RESSARCIR OS FAMILIARES DA VÍTIMA? SEGUNDO A ONU, CERCA DE 2,5 MILHÕES DE PESSOAS POR ANO EM TODO O MUNDO SÃO VÍTIMAS DO TRÁFICO INTERNACIONAL.","color":"#008000"}]',
1,8);

INSERT INTO `questions` (`id`, `text`, `content`, `active`, `order_index`) VALUES
(9,
'09 — E SE A PESSOA RAPTADA FOSSE UM ENTE QUERIDO SEU (ESPOSA, ESPOSO, FILHO, FILHA, MÃE, PAI, IRMÃO, IRMÃ), VOCÊ SERIA A FAVOR DA “PENA DE MORTE” PARA O RAPTOR?',
'[{"bold":true,"text":"09 — E SE A PESSOA RAPTADA FOSSE UM ENTE QUERIDO SEU, VOCÊ SERIA A FAVOR DA ","color":"#0000FF"},{"bold":true,"text":"“PENA DE MORTE” PARA O RAPTOR?","color":"#FF0000"}]',
1,9);

INSERT INTO `questions` (`id`, `text`, `content`, `active`, `order_index`) VALUES
(10,
'10 — VOCÊ É A FAVOR DA “PENA DE MORTE” PARA POLÍTICOS OU FUNCIONÁRIOS PÚBLICOS (CIVIS OU MILITARES) QUE DESVIAM DINHEIRO PÚBLICO (PECULATO)? ESSE É UM CRIME CONTRA O POVO E DEVE SER CONSIDERADO (GENOCÍDIO), E OS BENS DOS CULPADOS SERIAM ESPOLIADOS PARA RESSARCIR O ESTADO BRASILEIRO. MAIS DE 153.000 DOENTES MORREM TODOS OS ANOS NO SUS POR FALTA DE MÉDICOS, EM CONSEQUÊNCIA DOS MAIS DE 300 BILHÕES DE REAIS QUE SÃO DESVIADOS ANUALMENTE.',
'[{"bold":true,"text":"10 — VOCÊ É A FAVOR DA ","color":"#0000FF"},{"bold":true,"text":"“PENA DE MORTE” PARA POLÍTICOS OU FUNCIONÁRIOS PÚBLICOS","color":"#FF0000"},{"bold":true,"text":" QUE DESVIAM DINHEIRO PÚBLICO? MAIS DE 153.000 DOENTES MORREM TODOS OS ANOS NO SUS EM CONSEQUÊNCIA DOS DESVIOS.","color":"#008000"}]',
1,10);

INSERT INTO `questions` (`id`, `text`, `content`, `active`, `order_index`) VALUES
(11,
'11 — VOCÊ ACHA QUE O BANDIDO QUE DÁ UM TIRO NA CABEÇA DE UMA PESSOA INDEFESA É MAIS IMPIEDOSO DO QUE O POLÍTICO QUE DESVIA 100 MILHÕES DOS COFRES PÚBLICOS? O BANDIDO MATA APENAS UM, ENQUANTO O POLÍTICO MATA MILHARES: CERCA DE 153 MIL MORTES POR ANO SÃO CAUSADAS POR MAU ATENDIMENTO, FALTA DE MÉDICOS OU FALTA DE MEDICAMENTOS NO SUS DEVIDO AO DESVIO DE VERBAS DO ESTADO.',
'[{"bold":true,"text":"11 — VOCÊ ACHA QUE O BANDIDO QUE DÁ UM TIRO NA CABEÇA DE UMA PESSOA INDEFESA É MAIS IMPIEDOSO DO QUE O POLÍTICO QUE DESVIA ","color":"#0000FF"},{"bold":true,"text":"100 MILHÕES DOS COFRES PÚBLICOS?","color":"#FF0000"},{"bold":true,"text":" CERCA DE 153 MIL MORTES POR ANO SÃO CAUSADAS POR MAU ATENDIMENTO, FALTA DE MÉDICOS OU FALTA DE MEDICAMENTOS NO SUS.","color":"#008000"}]',
1,11);

INSERT INTO `questions` (`id`, `text`, `content`, `active`, `order_index`) VALUES
(12,
'12 — VOCÊ É A FAVOR DA "LEI GANDHI ANTI-AUMENTO SALARIAL DOS POLÍTICOS"? ELA PROIBIRIA OS PARLAMENTARES DE VOTAREM EM PROJETOS DE LEI QUE VISEM AUMENTAR SEUS PRÓPRIOS SALÁRIOS. ISSO PASSARIA A SER FEITO POR COMISSÕES INDEPENDENTES E SANCIONADO PELO PRESIDENTE DA REPÚBLICA OU PELO STF, DE ACORDO COM O PERCENTUAL DA INFLAÇÃO, COMO OCORRE COM QUALQUER TRABALHADOR BRASILEIRO.',
'[{"bold":true,"text":"12 — VOCÊ É A FAVOR DA ","color":"#0000FF"},{"bold":true,"text":"\\"LEI GANDHI ANTI-AUMENTO SALARIAL DOS POLÍTICOS\\"","color":"#FF0000"},{"bold":true,"text":"? ISSO PASSARIA A SER FEITO POR COMISSÕES INDEPENDENTES E SANCIONADO PELO PRESIDENTE DA REPÚBLICA OU PELO STF.","color":"#008000"}]',
1,12);

INSERT INTO `questions` (`id`, `text`, `content`, `active`, `order_index`) VALUES
(13,
'13 — VOCÊ É A FAVOR DA "LEI GANDHI DE PROTEÇÃO À VÍTIMA DE RAPTO"? ELA OBRIGARIA O RAPTOR, SOB PENA DE CHICOTADAS, A CONFESSAR ONDE ESCONDEU A VÍTIMA POUCAS HORAS ANTES DE SUA PRISÃO (APENAS EM CASOS DE RAPTO RECENTE E IMEDIATO, ONDE HAJA A POSSIBILIDADE DE A VÍTIMA AINDA ESTAR VIVA). O ARTIGO 5º, INCISO III DA CONSTITUIÇÃO, QUE DIZ: "NINGUÉM SERÁ SUBMETIDO A TORTURA NEM A TRATAMENTO DESUMANO OU DEGRADANTE", SÓ PROTEGE O BANDIDO?',
'[{"bold":true,"text":"13 — VOCÊ É A FAVOR DA ","color":"#0000FF"},{"bold":true,"text":"\\"LEI GANDHI DE PROTEÇÃO À VÍTIMA DE RAPTO\\"","color":"#FF0000"},{"bold":true,"text":"? O ARTIGO 5º, INCISO III DA CONSTITUIÇÃO, DIZ: \\"NINGUÉM SERÁ SUBMETIDO A TORTURA NEM A TRATAMENTO DESUMANO OU DEGRADANTE\\".","color":"#008000"}]',
1,13);

INSERT INTO `questions` (`id`, `text`, `content`, `active`, `order_index`) VALUES
(14,
'14 — VOCÊ CONCORDA COM A "LEI GANDHI DE PROTEÇÃO À SAÚDE, À EDUCAÇÃO E À PESQUISA"? ELA PROPÕE QUE A VERBA DESTINADA A ESSAS ÁREAS SEJA SEMPRE AUMENTADA PERCENTUALMENTE NO MÍNIMO IGUAL OU ACIMA DA INFLAÇÃO, JAMAIS PODENDO SER DIMINUÍDA. ALÉM DISSO, PROPÕE UMA EMENDA CONSTITUCIONAL PARA TRANSFORMAR A REFERIDA LEI EM "CLÁUSULA PÉTREA" (OU SEJA, IMUTÁVEL). ATUALMENTE, QUANDO O GOVERNO PRECISA DE MAIS DINHEIRO, SEMPRE O RETIRA DA SAÚDE, DA EDUCAÇÃO E DA PESQUISA CIENTÍFICA.',
'[{"bold":true,"text":"14 — VOCÊ CONCORDA COM A ","color":"#0000FF"},{"bold":true,"text":"\\"LEI GANDHI DE PROTEÇÃO À SAÚDE, À EDUCAÇÃO E À PESQUISA\\"","color":"#FF0000"},{"bold":true,"text":"? ELA PROPÕE QUE A VERBA DESTINADA A ESSAS ÁREAS SEJA SEMPRE AUMENTADA NO MÍNIMO IGUAL OU ACIMA DA INFLAÇÃO.","color":"#008000"}]',
1,14);

INSERT INTO `questions` (`id`, `text`, `content`, `active`, `order_index`) VALUES
(15,
'15 — VOCÊ É A FAVOR DA “PENA DE MORTE” PARA ASSASSINOS MENORES DE 18 ANOS, MAS QUE TENHAM ACIMA DE 12 ANOS? A LEI DA INIMPUTABILIDADE PARA MENORES DE 18 ANOS É INCONSTITUCIONAL; NA VERDADE, O QUE A LEI ESTÁ DIZENDO É QUE O MENOR PODE MATAR. MESMO ASSIM, ELA PASSOU NO CONGRESSO E TEVE O AVAL DO STF, OS GUARDIÕES DA CONSTITUIÇÃO (ART. 102: "COMPETE AO SUPREMO TRIBUNAL FEDERAL, PRECIPUAMENTE, A GUARDA DA CONSTITUIÇÃO, CABENDO-LHE...").',
'[{"bold":true,"text":"15 — VOCÊ É A FAVOR DA ","color":"#0000FF"},{"bold":true,"text":"“PENA DE MORTE” PARA ASSASSINOS MENORES DE 18 ANOS","color":"#FF0000"},{"bold":true,"text":"? A LEI DA INIMPUTABILIDADE PARA MENORES DE 18 ANOS É APRESENTADA AQUI COMO INCONSTITUCIONAL.","color":"#008000"}]',
1,15);

INSERT INTO `questions` (`id`, `text`, `content`, `active`, `order_index`) VALUES
(16,
'16 — VOCÊ É A FAVOR DA “PENA DE MORTE” PARA POLICIAL ASSASSINO DE PESSOA DESARMADA E INDEFESA, E DE QUE OS SEUS BENS SEJAM ESPOLIADOS PARA RESSARCIR OS FAMILIARES DA VÍTIMA? HOUVE 6.413 ÓBITOS CAUSADOS PELA POLÍCIA EM 2024, E MUITOS DELES ERAM DE PESSOAS INOCENTES.',
'[{"bold":true,"text":"16 — VOCÊ É A FAVOR DA ","color":"#0000FF"},{"bold":true,"text":"“PENA DE MORTE” PARA POLICIAL ASSASSINO DE PESSOA DESARMADA E INDEFESA","color":"#FF0000"},{"bold":true,"text":"? HOUVE 6.413 ÓBITOS CAUSADOS PELA POLÍCIA EM 2024.","color":"#008000"}]',
1,16);

INSERT INTO `questions` (`id`, `text`, `content`, `active`, `order_index`) VALUES
(17,
'17 — VOCÊ É A FAVOR DA "PENA DE MORTE" PARA POLICIAL CÚMPLICE E FALSA TESTEMUNHA EM FAVOR DE POLICIAL ASSASSINO DE PESSOA DESARMADA E INDEFESA, COM A ESPOLIAÇÃO DE SEUS BENS PARA RESSARCIR OS FAMILIARES DA VÍTIMA?',
'[{"bold":true,"text":"17 — VOCÊ É A FAVOR DA ","color":"#0000FF"},{"bold":true,"text":"\\"PENA DE MORTE\\" PARA POLICIAL CÚMPLICE E FALSA TESTEMUNHA","color":"#FF0000"},{"bold":true,"text":" EM FAVOR DE POLICIAL ASSASSINO DE PESSOA DESARMADA E INDEFESA?","color":"#008000"}]',
1,17);

INSERT INTO `questions` (`id`, `text`, `content`, `active`, `order_index`) VALUES
(18,
'18 — VOCÊ É A FAVOR DA "PENA DE MORTE" PARA BANDIDOS QUE EXPLODEM CAIXAS ELETRÔNICOS (MULTIBANCO)? ISSO SERIA CLASSIFICADO COMO CRIME CONTRA O POVO (TERRORISMO, CRIME HEDIONDO). EM MUITAS CIDADES DO INTERIOR, IDOSOS PRECISAM VIAJAR DE 80 A 100 KM APENAS PARA SACAR DINHEIRO POR CAUSA DESSE CRIME.',
'[{"bold":true,"text":"18 — VOCÊ É A FAVOR DA ","color":"#0000FF"},{"bold":true,"text":"\\"PENA DE MORTE\\" PARA BANDIDOS QUE EXPLODEM CAIXAS ELETRÔNICOS","color":"#FF0000"},{"bold":true,"text":"? EM MUITAS CIDADES DO INTERIOR, IDOSOS PRECISAM VIAJAR DE 80 A 100 KM APENAS PARA SACAR DINHEIRO POR CAUSA DESSE CRIME.","color":"#008000"}]',
1,18);

INSERT INTO `questions` (`id`, `text`, `content`, `active`, `order_index`) VALUES
(19,
'19 — VOCÊ É A FAVOR DA "PENA DE MORTE" PARA BANDIDOS QUE, EM ASSALTOS, EXPLODEM AS CAIXAS ELETRÔNICOS E USAM REFÉNS COMO ESCUDO HUMANO? ISSO DEMONSTRA TOTAL DESRESPEITO À VIDA ALHEIA, CONFIGURANDO UM CRIME CONTRA O POVO (TERRORISMO).',
'[{"bold":true,"text":"19 — VOCÊ É A FAVOR DA ","color":"#0000FF"},{"bold":true,"text":"\\"PENA DE MORTE\\" PARA BANDIDOS QUE USAM REFÉNS COMO ESCUDO HUMANO","color":"#FF0000"},{"bold":true,"text":"? ISSO DEMONSTRA TOTAL DESRESPEITO À VIDA ALHEIA.","color":"#008000"}]',
1,19);

INSERT INTO `questions` (`id`, `text`, `content`, `active`, `order_index`) VALUES
(20,
'20 — CASO NÃO SEJA A FAVOR DA "PENA DE MORTE", VOCÊ É A FAVOR DA "LEI GANDHI ANTI-HOMICÍDIO"? ELA PROPÕE QUE O CRIME DE HOMICÍDIO SEJA IMPRESCRITÍVEL, INAFIANÇÁVEL E COM CUMPRIMENTO INTEGRAL DA PENA NOS SEGUINTES MOLDES: SE ALGUÉM AGREDIR UMA PESSOA HUMANA — FERINDO-A, MUTILANDO-A, INCENDIANDO-A OU CAUSANDO-LHE MALES E DEFORMAÇÕES FÍSICAS —, QUE SEJA FEITO O MESMO AO AGRESSOR, NA MESMA PROPORÇÃO. SOMA-SE A ISSO A PENA DE PRISÃO PREVISTA EM LEI COM CUMPRIMENTO INTEGRAL, A ESPOLIAÇÃO DE SEUS BENS PARA INDENIZAÇÃO À VÍTIMA E, CASO SEJA NECESSÁRIO O TRANSPLANTE DE ALGUM ÓRGÃO (RINS, PULMÃO, ETC.), O AGRESSOR SERIA UM DOADOR COMPULSÓRIO. SE O ÓRGÃO NÃO FOR COMPATÍVEL, SERIA DOADO AO SUS, COLOCANDO A VÍTIMA COMO O PRIMEIRO PACIENTE NA FILA DE ESPERA. ATUALMENTE, O HOMICÍDIO PRESCREVE EM 20 ANOS (ART. 109 DO CÓDIGO PENAL), MAS O MORTO PERMANECE MORTO (A MORTE NÃO PRESCREVE). (NOTA: AJUSTEI O ARTIGO CITADO DE 21 PARA 109, QUE É O QUE REGE A PRESCRIÇÃO NO CÓDIGO PENAL BRASILEIRO).',
'[{"bold":true,"text":"20 — CASO NÃO SEJA A FAVOR DA ","color":"#0000FF"},{"bold":true,"text":"\\"LEI GANDHI ANTI-HOMICÍDIO\\"","color":"#FF0000"},{"bold":true,"text":"? ATUALMENTE, O HOMICÍDIO PRESCREVE EM 20 ANOS (ART. 109 DO CÓDIGO PENAL), MAS O MORTO PERMANECE MORTO.","color":"#008000"}]',
1,20);

INSERT INTO `questions` (`id`, `text`, `content`, `active`, `order_index`) VALUES
(21,
'21 — VOCÊ É A FAVOR DA "PENA DE MORTE" PARA O FUNCIONÁRIO QUE DESVIA (E NÃO PULVERIZA) 1.000 LITROS DE SUBSTÂNCIA QUÍMICA DESTINADA A MATAR O MOSQUITO DA ZIKA, DENGUE E CHIKUNGUNYA NA CIDADE? ESTE SERIA UM CRIME CONTRA O POVO (GENOCÍDIO). ESTA PERGUNTA É UM TESTE PARA A SUA CONSCIÊNCIA, RESPONSABILIDADE E PARA VER SE VOCÊ É UMA PESSOA CONSEQUENTE.',
'[{"bold":true,"text":"21 — VOCÊ É A FAVOR DA ","color":"#0000FF"},{"bold":true,"text":"\\"PENA DE MORTE\\" PARA O FUNCIONÁRIO QUE DESVIA 1.000 LITROS DE SUBSTÂNCIA QUÍMICA","color":"#FF0000"},{"bold":true,"text":" DESTINADA A MATAR O MOSQUITO DA ZIKA, DENGUE E CHIKUNGUNYA NA CIDADE?","color":"#008000"}]',
1,21);

INSERT INTO `questions` (`id`, `text`, `content`, `active`, `order_index`) VALUES
(22,
'22 — VOCÊ É A FAVOR DA "PENA DE MORTE" PARA POLÍTICOS, FUNCIONÁRIOS PÚBLICOS OU POLICIAIS CORRUPTOS (ATIVOS OU PASSIVOS) QUE SUBORNAM OU DEIXAM-SE SUBORNAR? O CÂNCER DO BRASIL É A CORRUPÇÃO E PRECISAMOS EXTIRPÁ-LA. CERCA DE 300 BILHÕES DE REAIS POR ANO SÃO DESVIADOS ATRAVÉS DA CORRUPÇÃO.',
'[{"bold":true,"text":"22 — VOCÊ É A FAVOR DA ","color":"#0000FF"},{"bold":true,"text":"\\"PENA DE MORTE\\" PARA POLÍTICOS, FUNCIONÁRIOS PÚBLICOS OU POLICIAIS CORRUPTOS","color":"#FF0000"},{"bold":true,"text":"? CERCA DE 300 BILHÕES DE REAIS POR ANO SÃO DESVIADOS ATRAVÉS DA CORRUPÇÃO.","color":"#008000"}]',
1,22);

INSERT INTO `questions` (`id`, `text`, `content`, `active`, `order_index`) VALUES
(23,
'23 — VOCÊ É A FAVOR DA "PENA DE MORTE" PARA O GARIMPO ILEGAL QUE UTILIZA MERCÚRIO E SUBSTÂNCIAS TÓXICAS PROIBIDAS? TRATA-SE DE UM CRIME CONTRA O POVO (GENOCÍDIO). MUITOS INDÍGENAS JÁ NASCEM TETRAPLÉGICOS POR AÇÃO DO MERCÚRIO. EM MUITAS CIDADES DO AMAZONAS, OS PEIXES ESTÃO IMPRÓPRIOS PARA O CONSUMO POR CAUSA DISSO, E OS LENÇÓIS FREÁTICOS CONTAMINADOS AFETAM TODA A NAÇÃO.',
'[{"bold":true,"text":"23 — VOCÊ É A FAVOR DA ","color":"#0000FF"},{"bold":true,"text":"\\"PENA DE MORTE\\" PARA O GARIMPO ILEGAL QUE UTILIZA MERCÚRIO","color":"#FF0000"},{"bold":true,"text":" E SUBSTÂNCIAS TÓXICAS PROIBIDAS? OS LENÇÓIS FREÁTICOS CONTAMINADOS AFETAM TODA A NAÇÃO.","color":"#008000"}]',
1,23);

INSERT INTO `questions` (`id`, `text`, `content`, `active`, `order_index`) VALUES
(24,
'24 — CASO VOCÊ TENHA DISCORDADO DA "PENA DE MORTE EM CARÁTER EFETIVO" PARA ASSASSINOS E POLÍTICOS QUE DESVIAM DINHEIRO PÚBLICO, VOCÊ SERIA A FAVOR DA "LEI DA PENA DE MORTE EM CARÁTER EXPERIMENTAL"? ELA SERIA APLICADA POR APENAS 4 ANOS E, CASO DIMINUÍSSE SIGNIFICATIVAMENTE (60%) OS REFERIDOS CRIMES, A LEI TORNAR-SE-IA PERMANENTE.',
'[{"bold":true,"text":"24 — CASO VOCÊ TENHA DISCORDADO DA ","color":"#0000FF"},{"bold":true,"text":"\\"LEI DA PENA DE MORTE EM CARÁTER EXPERIMENTAL\\"","color":"#FF0000"},{"bold":true,"text":"? ELA SERIA APLICADA POR APENAS 4 ANOS E, CASO DIMINUÍSSE SIGNIFICATIVAMENTE (60%) OS REFERIDOS CRIMES, A LEI TORNAR-SE-IA PERMANENTE.","color":"#008000"}]',
1,24);

INSERT INTO `questions` (`id`, `text`, `content`, `active`, `order_index`) VALUES
(25,
'25 — VOCÊ É A FAVOR DA "PENA DE MORTE" PARA FALSIFICADORES E TRAFICANTES DE MEDICAMENTOS FALSIFICADOS? SEGUNDO A OMS, 10% DOS MEDICAMENTOS NO MUNDO SÃO FALSIFICADOS.',
'[{"bold":true,"text":"25 — VOCÊ É A FAVOR DA ","color":"#0000FF"},{"bold":true,"text":"\\"PENA DE MORTE\\" PARA FALSIFICADORES E TRAFICANTES DE MEDICAMENTOS FALSIFICADOS","color":"#FF0000"},{"bold":true,"text":"? SEGUNDO A OMS, 10% DOS MEDICAMENTOS NO MUNDO SÃO FALSIFICADOS.","color":"#008000"}]',
1,25);

INSERT INTO `questions` (`id`, `text`, `content`, `active`, `order_index`) VALUES
(26,
'26 — VOCÊ É A FAVOR DA "PENA DE MORTE" PARA TRAFICANTES DE DROGAS PESADAS (COCAÍNA, CRACK, HEROÍNA, LSD, MORFINA, FENTANIL, XILAZINA, ETC.)?',
'[{"bold":true,"text":"26 — VOCÊ É A FAVOR DA ","color":"#0000FF"},{"bold":true,"text":"\\"PENA DE MORTE\\" PARA TRAFICANTES DE DROGAS PESADAS","color":"#FF0000"},{"bold":true,"text":" (COCAÍNA, CRACK, HEROÍNA, LSD, MORFINA, FENTANIL, XILAZINA, ETC.)?","color":"#008000"}]',
1,26);

INSERT INTO `questions` (`id`, `text`, `content`, `active`, `order_index`) VALUES
(27,
'27 — VOCÊ É A FAVOR DA "SUSPENSÃO IMEDIATA DA IMUNIDADE DIPLOMÁTICA OU IMUNIDADE PARLAMENTAR DOS POLÍTICOS" PARA FINS JURÍDICOS OU PENAIS QUANDO ELES FOREM SUSPEITOS DE CRIMES? O OBJETIVO SERIA FAZER COM QUE ELES SEJAM INVESTIGADOS E JULGADOS AINDA NO EXERCÍCIO DO MANDATO PARLAMENTAR. A IMUNIDADE DIPLOMÁTICA/PARLAMENTAR, NESSES CASOS, SÓ PROTEGE O BANDIDO E É INCONSTITUCIONAL, POIS FERE O ARTIGO 5º DA CONSTITUIÇÃO, QUE DIZ: "TODOS SÃO IGUAIS PERANTE A LEI".',
'[{"bold":true,"text":"27 — VOCÊ É A FAVOR DA ","color":"#0000FF"},{"bold":true,"text":"\\"SUSPENSÃO IMEDIATA DA IMUNIDADE DIPLOMÁTICA OU IMUNIDADE PARLAMENTAR DOS POLÍTICOS\\"","color":"#FF0000"},{"bold":true,"text":" PARA FINS JURÍDICOS OU PENAIS QUANDO ELES FOREM SUSPEITOS DE CRIMES?","color":"#008000"}]',
1,27);

INSERT INTO `questions` (`id`, `text`, `content`, `active`, `order_index`) VALUES
(28,
'28 — VOCÊ É A FAVOR DA "PENA DE MORTE" PARA INCENDIÁRIOS FLORESTAIS CRIMINOSOS, DESMATAMENTO ILEGAL E TRÁFICO DE MADEIRA DE ÁRVORES EM VIAS DE EXTINÇÃO? MUNDIALMENTE, A FUMAÇA DE INCÊNDIOS PROVOCOU 154 MIL MORTES APENAS EM 2024, ALÉM DE MILHARES DE INTERNAÇÕES QUE GERAM PREJUÍZOS AOS COFRES PÚBLICOS.',
'[{"bold":true,"text":"28 — VOCÊ É A FAVOR DA ","color":"#0000FF"},{"bold":true,"text":"\\"PENA DE MORTE\\" PARA INCENDIÁRIOS FLORESTAIS CRIMINOSOS","color":"#FF0000"},{"bold":true,"text":", DESMATAMENTO ILEGAL E TRÁFICO DE MADEIRA DE ÁRVORES EM VIAS DE EXTINÇÃO? MUNDIALMENTE, A FUMAÇA DE INCÊNDIOS PROVOCOU 154 MIL MORTES APENAS EM 2024.","color":"#008000"}]',
1,28);

INSERT INTO `questions` (`id`, `text`, `content`, `active`, `order_index`) VALUES
(29,
'29 — VOCÊ É A FAVOR DA "LEI GANDHI ANTI-ATROPELAMENTO"? ELA OBRIGARIA O MOTORISTA QUE, DIRIGINDO EMBRIAGADO, ATROPELASSE ALGUÉM, A TER SEUS BENS ESPOLIADOS PARA INDENIZAR A VÍTIMA. O CRIME SERIA INAFIANÇÁVEL, SOMADO À PENA DE PRISÃO DESCRITA EM LEI COM CUMPRIMENTO INTEGRAL.',
'[{"bold":true,"text":"29 — VOCÊ É A FAVOR DA ","color":"#0000FF"},{"bold":true,"text":"\\"LEI GANDHI ANTI-ATROPELAMENTO\\"","color":"#FF0000"},{"bold":true,"text":"? ELA OBRIGARIA O MOTORISTA EMBRIAGADO A TER SEUS BENS ESPOLIADOS PARA INDENIZAR A VÍTIMA.","color":"#008000"}]',
1,29);

INSERT INTO `questions` (`id`, `text`, `content`, `active`, `order_index`) VALUES
(30,
'30 — VOCÊ É A FAVOR DA "LEI GANDHI ANTI-FUGA DE MENORES INFRATORES" DA INSTITUIÇÃO DE RESSOCIALIZAÇÃO ONDE CUMPREM A MEDIDA SOCIOEDUCATIVA? CASO HAJA FUGA, O MENOR ASSUMIRIA A MAIORIDADE PENAL, CUMPRINDO O RESTANTE DO TEMPO EM UMA PRISÃO VOLTADA PARA MENORES.',
'[{"bold":true,"text":"30 — VOCÊ É A FAVOR DA ","color":"#0000FF"},{"bold":true,"text":"\\"LEI GANDHI ANTI-FUGA DE MENORES INFRATORES\\"","color":"#FF0000"},{"bold":true,"text":" DA INSTITUIÇÃO DE RESSOCIALIZAÇÃO ONDE CUMPREM A MEDIDA SOCIOEDUCATIVA?","color":"#008000"}]',
1,30);

INSERT INTO `questions` (`id`, `text`, `content`, `active`, `order_index`) VALUES
(31,
'31 — VOCÊ É A FAVOR QUE O ESTADO BRASILEIRO FORNEÇA AO DEPENDENTE QUÍMICO A DROGA NECESSÁRIA PARA O SEU CONSUMO SEMANAL? POSTERIORMENTE, O ESTADO PODERIA SUBSTITUIR A DROGA PESADA POR OUTRA QUE CAUSE MENOS DEPENDÊNCIA E AJUDE NA CURA DO INDIVÍDUO. ESSA MEDIDA VISARIA DIMINUIR O NÚMERO DE ASSALTOS E MORTES CAUSADOS PELO VÍCIO.',
'[{"bold":true,"text":"31 — VOCÊ É A FAVOR QUE O ESTADO BRASILEIRO FORNEÇA AO DEPENDENTE QUÍMICO A DROGA NECESSÁRIA PARA O SEU CONSUMO SEMANAL? ","color":"#0000FF"},{"bold":true,"text":"POSTERIORMENTE, O ESTADO PODERIA SUBSTITUIR A DROGA PESADA","color":"#FF0000"},{"bold":true,"text":" POR OUTRA QUE CAUSE MENOS DEPENDÊNCIA E AJUDE NA CURA DO INDIVÍDUO.","color":"#008000"}]',
1,31);

INSERT INTO `questions` (`id`, `text`, `content`, `active`, `order_index`) VALUES
(32,
'32 — VOCÊ É A FAVOR DA "PENA DE MORTE PARA HACKERS" QUE ENTRAM VIA INTERNET E DANIFICAM SITES PÚBLICOS COMO O DO MINISTÉRIO DA SAÚDE, DO SUS, DE HOSPITAIS, DE CASAS DE SAÚDE E DE MATERNIDADES, CAUSANDO MORTES E PREJUDICANDO A SAÚDE DE MILHARES DE VIDAS? ISSO SERIA CONSIDERADO UM CRIME CONTRA O POVO (GENOCÍDIO, TERRORISMO CIBERNÉTICO).',
'[{"bold":true,"text":"32 — VOCÊ É A FAVOR DA ","color":"#0000FF"},{"bold":true,"text":"\\"PENA DE MORTE PARA HACKERS\\"","color":"#FF0000"},{"bold":true,"text":" QUE DANIFICAM SITES PÚBLICOS E CAUSAM MORTES, PREJUDICANDO A SAÚDE DE MILHARES DE VIDAS?","color":"#008000"}]',
1,32);

INSERT INTO `questions` (`id`, `text`, `content`, `active`, `order_index`) VALUES
(33,
'33 — VOCÊ É A FAVOR DA "LEI GANDHI" PARA A CRIAÇÃO OFICIAL DA FFGF (FORÇA FEDERAL GUARDIÕES DA FLORESTA), COMPOSTA POR INDÍGENAS TREINADOS, ARMADOS MILITAR E TECNOLOGICAMENTE, E INCORPORADOS À POLÍCIA FEDERAL? QUEM ENTENDE E VIVE NA FLORESTA É O INDÍGENA, PODENDO PRESTAR UMA MELHOR VIGILÂNCIA.',
'[{"bold":true,"text":"33 — VOCÊ É A FAVOR DA ","color":"#0000FF"},{"bold":true,"text":"\\"LEI GANDHI\\" PARA A CRIAÇÃO OFICIAL DA FFGF","color":"#FF0000"},{"bold":true,"text":" (FORÇA FEDERAL GUARDIÕES DA FLORESTA), COMPOSTA POR INDÍGENAS TREINADOS E INCORPORADOS À POLÍCIA FEDERAL?","color":"#008000"}]',
1,33);

INSERT INTO `questions` (`id`, `text`, `content`, `active`, `order_index`) VALUES
(34,
'34 — VOCÊ É A FAVOR DA "PENA DE MORTE" PARA BANDIDOS PORTANDO OU EXIBINDO ARMAS DE GUERRA (COMO METRALHADORA, FUZIL, GRANADA, DINAMITE E NITROGLICERINA) EM VIA PÚBLICA?',
'[{"bold":true,"text":"34 — VOCÊ É A FAVOR DA ","color":"#0000FF"},{"bold":true,"text":"\\"PENA DE MORTE\\" PARA BANDIDOS PORTANDO OU EXIBINDO ARMAS DE GUERRA","color":"#FF0000"},{"bold":true,"text":" EM VIA PÚBLICA?","color":"#008000"}]',
1,34);

INSERT INTO `questions` (`id`, `text`, `content`, `active`, `order_index`) VALUES
(35,
'35 — VOCÊ É A FAVOR DA "LEI GANDHI ANTI-FUNCIONÁRIO FANTASMA"? ELA OBRIGARIA TODO PARLAMENTAR EM FIM DE MANDATO A ENTREGAR À AUTORIDADE RESPONSÁVEL A LISTA DE TODOS OS FUNCIONÁRIOS E ASSESSORES AO SEU SERVIÇO PARA AS DEVIDAS EXONERAÇÕES, EVITANDO SOBRECARREGAR O SETOR PÚBLICO. A DESOBEDIÊNCIA RESULTARIA EM UMA PENA DE 10 ANOS DE PRISÃO E MULTA DE 100 MIL REAIS PARA O POLÍTICO, ALÉM DE 15 ANOS DE PRISÃO PARA O FUNCIONÁRIO FANTASMA.',
'[{"bold":true,"text":"35 — VOCÊ É A FAVOR DA ","color":"#0000FF"},{"bold":true,"text":"\\"LEI GANDHI ANTI-FUNCIONÁRIO FANTASMA\\"","color":"#FF0000"},{"bold":true,"text":"? A DESOBEDIÊNCIA RESULTARIA EM PENA DE PRISÃO E MULTA PARA O POLÍTICO E PARA O FUNCIONÁRIO FANTASMA.","color":"#008000"}]',
1,35);

INSERT INTO `questions` (`id`, `text`, `content`, `active`, `order_index`) VALUES
(36,
'36 — VOCÊ É A FAVOR DA "LEI GANDHI DA DELAÇÃO PREMIADA" NOS SEGUINTES MOLDES: SE O ACUSADO NÃO COOPERAR COM A JUSTIÇA, A PENA AUMENTA EM 50%; SE COOPERAR, CUMPRE APENAS A PENA RECEBIDA? A ATUAL DELAÇÃO PREMIADA É UM VERDADEIRO PRÊMIO AOS CORRUPTOS.',
'[{"bold":true,"text":"36 — VOCÊ É A FAVOR DA ","color":"#0000FF"},{"bold":true,"text":"\\"LEI GANDHI DA DELAÇÃO PREMIADA\\"","color":"#FF0000"},{"bold":true,"text":" NOS SEGUINTES MOLDES: SE O ACUSADO NÃO COOPERAR COM A JUSTIÇA, A PENA AUMENTA EM 50%; SE COOPERAR, CUMPRE APENAS A PENA RECEBIDA?","color":"#008000"}]',
1,36);

INSERT INTO `questions` (`id`, `text`, `content`, `active`, `order_index`) VALUES
(37,
'37 — VOCÊ É A FAVOR DA "LEI GANDHI PACIENTE FELIZ", QUE PUNE MÉDICOS QUE FALTAM AO PLANTÃO NO SUS PARA ATENDER EM CLÍNICAS PARTICULARES OU EM SEUS PRÓPRIOS CONSULTÓRIOS, MESMO SENDO PAGOS PELO ESTADO? A LEI TAMBÉM PUNIRIA COM 10 ANOS DE PRISÃO OS COLEGAS CÚMPLICES QUE ABONAM AS FALTAS DOS MESMOS (CORPORATIVISMO). A PENA SERIA DE 10 ANOS DE PRISÃO EFETIVA E MULTA DE 100 MIL REAIS.',
'[{"bold":true,"text":"37 — VOCÊ É A FAVOR DA ","color":"#0000FF"},{"bold":true,"text":"\\"LEI GANDHI PACIENTE FELIZ\\"","color":"#FF0000"},{"bold":true,"text":", QUE PUNE MÉDICOS QUE FALTAM AO PLANTÃO NO SUS PARA ATENDER EM CLÍNICAS PARTICULARES OU EM SEUS PRÓPRIOS CONSULTÓRIOS?","color":"#008000"}]',
1,37);

INSERT INTO `questions` (`id`, `text`, `content`, `active`, `order_index`) VALUES
(38,
'38 — VOCÊ É A FAVOR DA "PENA DE MORTE" PARA VIOLADORES (ESTUPRADORES) DE MULHERES (MAIORES OU MENORES) E DE VULNERÁVEIS? O BRASIL TEM CERCA DE 822 MIL CASOS DE ESTUPRO A CADA ANO — DOIS POR MINUTO.',
'[{"bold":true,"text":"38 — VOCÊ É A FAVOR DA ","color":"#0000FF"},{"bold":true,"text":"\\"PENA DE MORTE\\" PARA VIOLADORES (ESTUPRADORES)","color":"#FF0000"},{"bold":true,"text":" DE MULHERES E DE VULNERÁVEIS? O BRASIL TEM CERCA DE 822 MIL CASOS DE ESTUPRO A CADA ANO.","color":"#008000"}]',
1,38);

INSERT INTO `questions` (`id`, `text`, `content`, `active`, `order_index`) VALUES
(39,
'39 — VOCÊ ACHA QUE O BRASIL TEM UMA DEMOCRACIA PLENA, AMPLA E IRRESTRITA? NO PASSADO, O MILITAR APOSENTAVA-SE COM O SOLDO ACIMA DO RECEBIDO QUANDO ESTAVA NA ATIVA. QUANDO UM JUIZ COMETE UM CRIME, ELE É APENAS EXONERADO DO CARGO E APOSENTADO — OU MELHOR, PREMIADO, POIS VAI RECEBER SEM TRABALHAR. O MILITAR APOSENTADO, OUTRORA, AO MORRER DEIXAVA A APOSENTADORIA PARA A ESPOSA, E A ESPOSA DEIXAVA PARA OS FILHOS PERPETUAMENTE. E TODOS SOMOS IGUAIS PERANTE A CONSTITUIÇÃO (ART. 5º DA CONST. FEDERAL). MAS ALGUNS SÃO MAIS IGUAIS QUE OUTROS.',
'[{"bold":true,"text":"39 — VOCÊ ACHA QUE O BRASIL TEM UMA ","color":"#0000FF"},{"bold":true,"text":"DEMOCRACIA PLENA, AMPLA E IRRESTRITA","color":"#FF0000"},{"bold":true,"text":"? TODOS SOMOS IGUAIS PERANTE A CONSTITUIÇÃO, MAS ALGUNS SÃO MAIS IGUAIS QUE OUTROS.","color":"#008000"}]',
1,39);

INSERT INTO `questions` (`id`, `text`, `content`, `active`, `order_index`) VALUES
(40,
'40 — VOCÊ É A FAVOR DA PENA DE MORTE PARA FALSOS MÉDICOS QUE EXERCEM ILEGALMENTE A MEDICINA, SEM O DIPLOMA DE FACULDADE, SEM O NÚMERO DO CRM E SEM A APROVAÇÃO DO CONSELHO REGIONAL DE MEDICINA?',
'[{"bold":true,"text":"40 — VOCÊ É A FAVOR DA ","color":"#0000FF"},{"bold":true,"text":"PENA DE MORTE PARA FALSOS MÉDICOS","color":"#FF0000"},{"bold":true,"text":" QUE EXERCEM ILEGALMENTE A MEDICINA, SEM O DIPLOMA DE FACULDADE, SEM O NÚMERO DO CRM E SEM A APROVAÇÃO DO CONSELHO REGIONAL DE MEDICINA?","color":"#008000"}]',
1,40);
